language: cpp, python

python:
    - "2.7.2"

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5

install: ./install.sh

script: 
    - tests/unit_tests.sh
    - tests/integration_tests.sh
